#spring:
#  data:
#    mongodb:
#      port: 27017
#      host: localhost
#      database: formation

spring:
  data:
    mongodb:
      uri: mongodb+srv://userprojet:Apple2022@cluster0.znabk5g.mongodb.net/cabinet_medical
